### ISSUE TITLE
[FEATURE] - Dockerize the Project

### ISSUE THREAD

**Issue by dvo-dev** [dvo-dev/go-get-started#3]
## Description

Add a `Dockerfile` file and `docker-compose.yml` to the project - this will expedite simulating run environments, and ease of usage regardless of system. These files can be placed at the root of the project for now.

## Acceptance Criteria

- [x] Add a [`Dockerfile`](https://docs.docker.com/engine/reference/builder/) to containerize `webapp`
  - [x] Use multi stage build, optimize the output as much as possible (i.e. size)
  - [x] The `Dockerfile` should ensure that all tests are passing without critical errors (i.e. run `make test`), and generate the executable with `make build`
   - [x] Once the container finishes setting up, run the webapp executable in the final stage build container (you can copy the webapp executable from the previous stage build to the final build)
 - [x] Validate that the `Dockerfile` works
   - [x] You should be able to build an image with the `Dockerfile`, e.g.  `docker build -t fibtest .` (run in project root)
   - [x] You should be able to run the container `docker run --publish 8080:8080 fibtest`
     - [x] Assert that the server is properly running by pinging the `health` endpoint, `curl -XGET localhost:8080/health` and ensuring the response is appropriate
- [x] Create a [`docker-compose.yml`](https://docs.docker.com/compose/) that props up the `webapp` container using the `Dockerfile` from the previous steps
  - [x] The `webapp` should be hosted on port `8080` 
  - [x] Additionally have docker-compose create a [`postgres`](https://hub.docker.com/_/postgres) container and run it on port `5432`, initialize the following as environment variables:
    - `POSTGRES_USER=admin`
    - `POSTGRES_PASSWORD=admin`
    - `POSTGRES_DB=app`
- [x] Validate the `docker-compose.yml` - run `docker-compose up`
  - [x] Confirm you can reach and get a healthy response from the `webapp`, similarly to the previous steps done when creating the `Dockerfile` 
  - [x] Confirm that the `postgres` instance is running on port 5432 by connecting to it via [`psql`](https://www.postgresql.org/docs/14/app-psql.html) or [`pgcli`](https://www.pgcli.com/) (my personal preference), using the above credentials
    - [x] Additionally create simple `Makefile` targets for devs to quickly establish a connection to the main `postgres` instance using both `psql` and `pgcli`, e.g. `make db-psql` or `make db-pgcli`

## Reference Project Examples
- [Dockerfile](https://github.com/dvo-dev/fibonacci-backend/blob/main/Dockerfile)
- [docker-compose](https://github.com/dvo-dev/fibonacci-backend/blob/main/docker-compose.yml)

## Things to Consider

- Resource allocations to webapp?
- Scalable config reading for potentially multiple setups

**Comment by alexander-ma** [comment]
I was able to login to postgres using the following command:
`pgcli -h localhost -p 5432 -U admin app`
